program: Homework1

Homework1: Building Playground Market House Office Driver
	
Building:
	javac Buildings.java	
Playground:
	javac Playgrounds.java
Market:
	javac Market.java
House:
	javac House.java
Office:
	javac Office.java
	
Driver:	
	javac Driver.java
	java Driver
	