program: Homework1

Homework1: Building Playground Market House Office AL_Street LL_Street LD_Street Driver
	
Building:
	javac Building.java	
Playground:
	javac Playground.java
Market:
	javac Market.java
House:
	javac House.java
Office:
	javac Office.java
AL_Street:
	javac AL_Street.java
LL_Street:
	javac AL_Street.java
LD_Street:
	javac AL_Street.java

Driver:	
	javac Driver.java
	java Driver
	